- name: launchpad and dock configuration
  shell: lporg load {{ role_path }}/files/organization.yaml

- name: Show battery percentage
  shell: "defaults write com.apple.menuextra.battery ShowPercent YES"

- name: Restart topbar
  shell: "killall SystemUIServer"

- name: Disable last seen apps in Dock
  shell: "defaults write com.apple.dock show-recents -bool FALSE"

- name: Set default folder when opening Finder
  shell: 'defaults write com.apple.finder NewWindowTarget -string "Pf"'

- name: Show status bar in Finder
  shell: "defaults write com.apple.finder ShowStatusBar -bool TRUE"

- name: Restart topbar
  shell: "killall Dock"
