# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew cask applications
cask_applications:
  - google-chrome
  - visual-studio-code
  - slack
  - iterm2
  - google-drive
  - docker
  - postman
  - table-plus
  - omnidisksweeper
  - vlc
  - keka
  - ngrok
  - firefox-developer-edition
  - android-studio
  - etcher
  - qbittorrent
  - monitorcontrol
  - devcleaner
  - garmin-express
  - stremio
  - nordvpn

dock_applications:
  - name: Launchpad
    path: /Applications/Launchpad.app
  - name: System Preferences
    path: /Applications/System Preferences.app
  - name: Google Chrome
    path: /Applications/Google Chrome.app
  - name: Calendrier
    path: /Applications/Calendar.app
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
  - name: iTerm
    path: /Applications/iTerm.app
  - name: Slack
    path: /Applications/Slack.app
  - name: TablePlus
    path: /Applications/TablePlus.app
  - name: Postman
    path: /Applications/Postman.app
