---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
homebrew:
  - git
  - java
  - node
  - yarn
  - zsh
  - curl
  - tree
  - wget
  - go
  - vim
  - mkcert
  - maven
  - htop
  - nmap

# npm global packages
npm:
  - git-open
