---
- name: setup nginx proxy for Docker
  docker_container:
    name: nginx_proxy
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /Users/nicolas/Library/Application Support/mkcert:/etc/nginx/certs:cached