---
- file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  loop: "{{ websites }}"

- name: Download archives
  unarchive:
    src: "{{ item.zip }}"
    dest: "{{ item.path }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
  when: "item.zip is defined"
  loop: "{{ websites }}"

- name: Clone repos
  git:
    repo: "{{ item.git }}"
    dest: "{{ item.path }}"
  when: "item.git is defined"
  loop: "{{ websites }}"
