---
- file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  loop: "{{ websites }}"

- name: Clone repos
  git:
    repo: "{{ item.git }}"
    dest: "{{ item.path }}"
  when: "item.git is defined"
  loop: "{{ websites }}"
