---
- name: Install MySQL-Python module
  pip:
    name: "{{ item }}"
  with_items:
    - pymysql

- name: Enable MySQL services
  command: brew services start mysql

- name: Create MySQL databases
  mysql_db:
    login_user: root
    login_password: ~
    name: "{{ item.db }}"
    state: present
  when: "item.db is defined"
  loop: "{{ websites }}"

- name: Create MySQL users
  mysql_user:
    login_user: root
    login_password: ~
    name: "{{ item.db }}"
    password: "{{ item.db }}"
    # priv: "{{ item.db }}.*:ALL"
    host: "%"
    state: present
  when: "item.db is defined"
  loop: "{{ websites }}"
