- name: homebrew installation
  include_tasks: homebrew.yml

- name: npm installation
  include_tasks: npm.yml

- name: oh my zsh installation
  include_tasks: oh-my-zsh.yml

- name: dotfiles installation
  include_tasks: dotfiles.yml
